# Generated by Django 5.2 on 2025-04-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(upload_to='car_image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_image_car', to='auction_app.car')),
            ],
        ),
    ]
